# Generated by Django 5.0.2 on 2024-03-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('director', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('length', models.DurationField(verbose_name='Продолжительность')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Рейтинг')),
                ('plot', models.TextField(verbose_name='Сюжет')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/', verbose_name='Постер')),
                ('actors', models.ManyToManyField(to='movies.actor', verbose_name='Актеры')),
                ('genres', models.ManyToManyField(to='movies.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Кинофильм',
                'verbose_name_plural': 'Кинофильмы',
            },
        ),
    ]
